openapi: 3.0.0
info:
  title: GoCloudApp API
  version: 0.0.1
  description: GoCloudApp API Definition
servers:
  - url: http://api.devcarlos.com/api
    description: Production API Server
  - url: http://localhost:9000/api
    description: Local API Server
tags:
  - name: Health
    description: API used for Health Check
  - name: Subscription
    description: API used for Subscription actions
components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    Subscription: # Subscription Schema
      type: object
      properties:
        id:
          type: integer
          format: int64
          uniqueItems: true
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        RUT:
          type: string
paths:
  /health-check:
    get:
      tags:
        - Health
      summary: API Health Check
      responses:
        '200':
          description: OK
        '400':
          description: Bad request.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A Subscription with the specified ID was not found.
        '5XX':
          description: Unexpected error.
  /landing/subscription:
    post:
      tags:
        - Subscription
      summary: User Subscription
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                RUT:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Bad request.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A Subscription with the specified ID was not found.
        '5XX':
          description: Unexpected error.  